name: CI

on:
  push:
  pull_request:

jobs:
  PHP_Lowest:
    name: PHP ${{ matrix.php-versions }} wth lowest dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0']
        experimental: [false]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: bcmath, ctype, fileinfo, json, mbstring, dom, ldap, pdo, tokenizer, xml, mysql, sqlite
        coverage: xdebug

    - name: Update to lowest php dependencies
      run: composer update --prefer-lowest
    - name: Install php dependencies
      run: composer install --dev --no-interaction
    - name: Execute tests without coverage
      run: vendor/bin/phpunit --testsuite="BigBlueButton unit test suite,BigBlueButton integration test suite"
   
  PHP:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4','8.0']
        experimental: [false]
        include:
          - php-versions: '8.1'
            experimental: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: bcmath, ctype, fileinfo, json, mbstring, dom, ldap, pdo, tokenizer, xml, mysql, sqlite
        coverage: xdebug
    - name: Install php dependencies
      run: composer install --dev --no-interaction
      continue-on-error: ${{ matrix.experimental }}
    - name: Execute code style check via php-cs-fixer
      run: vendor/bin/php-cs-fixer fix --dry-run
      continue-on-error: ${{ matrix.experimental }}
    - name: Execute tests with coverage
      if: ${{ !matrix.experimental }}
      run: |
        mkdir -p build/logs
        vendor/bin/phpunit --coverage-clover=build/logs/coverage.xml --testsuite="BigBlueButton unit test suite,BigBlueButton integration test suite"
    - name: Execute tests without coverage
      if: ${{ matrix.experimental }}
      run: vendor/bin/phpunit --testsuite="BigBlueButton test suite"
      continue-on-error: true
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ matrix.php-versions == '7.4' && env.COVERALLS_REPO_TOKEN != null }}
      run: vendor/bin/php-coveralls --coverage_clover=build/logs/coverage.xml -v
